version: '3.7'
services:
  app:
    container_name: app
    image: ${APP_IMAGE}
    restart: always
    environment:
      - NODE_ENV=development
      - MONGODB_URI_LOCAL=mongodb://${DB_HOST}:37018
      - SESSION_SECRET=${SESSION_SECRET}
      - FACEBOOK_ID=${FACEBOOK_ID}
      - FACEBOOK_SECRET=${FACEBOOK_SECRET}
    ports:
      - "3000:3000"
    depends_on:
      - "mongo-db"
  mongo-db:
    container_name: mongo-db
    image: mongo
    command: mongod --port 37018
    volumes:
      - mongo-data:/data/db
    ports:
      - "37018:37018"
volumes:
  mongo-data:
