version: '3.7'
services:
  app:
    container_name: app
    restart: always
    build: .
    environment:
      - NODE_ENV=development
      - MONGODB_URI_LOCAL=mongodb://mongo:27017
      - SESSION_SECRET=${SESSION_SECRET}
      - FACEBOOK_ID=${FACEBOOK_ID}
      - FACEBOOK_SECRET=${FACEBOOK_SECRET}
    ports:
      - "3000:3000"
    depends_on:
      - "mongo"
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
volumes:
  mongo-data:
